
Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/* # Prevent block-length cop triggering on RSpec describe
  